language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
script:
  - ./gradlew clean check stage
  - docker build -t therickys93/emergencybot .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push therickys93/emergencybot;
    fi
deploy:
  provider: heroku
  app: emergencynumbersbot
  api_key:
    secure: CpqUv9qzp1ePSsNECHkzoOv5iCG7VQ7fcwoFmth2U8ugWxFMcKUQOacT2TKJI9bd1OXFiweHz6CViEyFs1B/lgdfIRvH1MXf5lOyYl5dYw9VS+L49NqXkJi8OdV8p/B3WCw8j7yshbWfMukyANimnGq9mtwjHXwLMuJvpQ0b71qC/BEacZXhENwnIc2R45wclSpkrfS3FyvJaedH4AQR/CsPKHiCocV3WdTTDJbAuj0HGfxSLfWlIUJz5KzJAU+XtLWUurSof2YBHiKxybDgCGb882Sxu62+zQbnKO1v1KDCHOswp+TqRi7ccP2iXCJO+c/lzJKBYeeKV70L8gPEZqCemOV+SGzM434Px4c3dr2B96GDjFnoMWb01K8CwWWmaKicORzlYYm5PAid58Hi1VX6ldCYSlMr7biM7Tvq5DTnWGjwbEHukyXoRcsIxglbdaF3683uqnMYhei+k94lO2/81k0AditU4t+TQG4pylUnCBQFV71DSMQ4xfkJyJjzreMsmM48kCD8ks1al/SaPUpDHTGorrphE1ZsRl3IWGgiKuK7SNjj1G97ITxjcibTunnRpRefZS3bc3+UrPejOsh/JY+WrfK0ziv7gmtD5nrew9C7jpCH8PYp5EejOTFb7cCzovFl0FlpApNWrnMtocaojohxfsJxMZITUsneO+0=
